GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Edward Tivruski",
    "number": "021-2142142142",
    "id": 6
}
